const GET_COMPTABLE     ="GET_COMPTABLE"
const ADD_COMPTABLE     ="ADD_COMPTABLE"
const GET_ALL_COMPTABLES="GET_ALL_COMPTABLES"
const DELETE_COMPTABLE  =   "DELETE_COMPTABLE"
exports ={GET_COMPTABLE ,    
    ADD_COMPTABLE     ,
    GET_ALL_COMPTABLES,
    DELETE_COMPTABLE  }
